# Generated by Django 4.0.2 on 2022-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_add'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated_add'),
        ),
    ]
