# Generated by Django 4.0.2 on 2022-03-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
